[package]
name = "tchat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "4.3.4", features = ["derive"] }
socket2 = "0.5.3"
tokio = { version = "1.28.2", features = ["full"] }
